"""
generate_reference_data.py
==========================
Runs the Python reference implementation and saves outputs to
tests/reference_data/ for use by C++ unit tests.

Requirements:
    pip install numpy
    Python reference modules (polyinteg, integpoints) available on PYTHONPATH.

Usage:
    python tools/generate_reference_data.py
"""

import os
import sys
import numpy as np

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_DIR = os.path.join(REPO_ROOT, "tests", "reference_data")
os.makedirs(OUTPUT_DIR, exist_ok=True)


def gauss_pts_quad8():
    """Return 9 Gauss points (xi, eta) in Abaqus ordering for Quad8."""
    gp = np.sqrt(0.6)
    pts = []
    for eta in [-gp, 0.0, gp]:
        for xi in [-gp, 0.0, gp]:
            pts.append((xi, eta))
    return np.array(pts)


def quad8_shape(xi, eta):
    """Quad8 serendipity shape functions at (xi, eta)."""
    N = np.array([
        -0.25 * (1 - xi) * (1 - eta) * (1 + xi + eta),
        -0.25 * (1 + xi) * (1 - eta) * (1 - xi + eta),
        -0.25 * (1 + xi) * (1 + eta) * (1 - xi - eta),
        -0.25 * (1 - xi) * (1 + eta) * (1 + xi - eta),
         0.5  * (1 - xi**2) * (1 - eta),
         0.5  * (1 + xi)   * (1 - eta**2),
         0.5  * (1 - xi**2) * (1 + eta),
         0.5  * (1 - xi)   * (1 - eta**2),
    ])
    return N


def compute_gauss_pts_global(node_coords):
    """
    Compute global coordinates of 9 Gauss points for a Quad8 element.
    node_coords: (8, 2) array of [x, y]
    """
    nat = gauss_pts_quad8()
    gpts = []
    for xi, eta in nat:
        N = quad8_shape(xi, eta)
        x = N @ node_coords[:, 0]
        y = N @ node_coords[:, 1]
        gpts.append([x, y])
    return np.array(gpts)


def generate_basis_reference():
    """
    Generate Quad8 basis polynomial reference data.
    Uses a test element and saves the 9×9 basis matrix.
    """
    try:
        import polyinteg as pli
    except ImportError:
        print("WARNING: polyinteg not found. Generating synthetic basis reference instead.")
        _generate_basis_reference_synthetic()
        return

    # Test element: slightly distorted quad
    node_coords = np.array([
        [0.0,  0.0],
        [1.0,  0.0],
        [1.1,  1.0],
        [0.0,  1.0],
        [0.5,  0.0],
        [1.05, 0.5],
        [0.55, 1.0],
        [0.0,  0.5],
    ])

    gpts = compute_gauss_pts_global(node_coords)
    x = gpts[:, 0]
    y = gpts[:, 1]

    # Python reference: shift by last point
    P = pli.createpolys(x - x[-1], y - y[-1])

    out_file = os.path.join(OUTPUT_DIR, "quad8_basis_polys.txt")
    # Save as 9×9 (the 9 monomials used, full degree-2 basis)
    np.savetxt(out_file, P, fmt="%.15e",
               header="Quad8 basis polynomials (9x9), generated by Python reference")
    print(f"Saved: {out_file}")
    print(f"  Shape: {P.shape}")


def _generate_basis_reference_synthetic():
    """
    When polyinteg is not available, generate basis reference using numpy.
    Implements the same Vandermonde inversion for validation.
    """
    from numpy.linalg import solve

    node_coords = np.array([
        [0.0,  0.0],
        [1.0,  0.0],
        [1.1,  1.0],
        [0.0,  1.0],
        [0.5,  0.0],
        [1.05, 0.5],
        [0.55, 1.0],
        [0.0,  0.5],
    ])

    gpts = compute_gauss_pts_global(node_coords)
    x = gpts[:, 0] - gpts[-1, 0]
    y = gpts[:, 1] - gpts[-1, 1]

    # 9 monomials: {1, x, y, x², xy, y², x³, x²y, xy²} in Pascal order
    monomials = [
        (0, 0), (1, 0), (0, 1),  # degree 0-1
        (2, 0), (1, 1), (0, 2),  # degree 2
        (3, 0), (2, 1), (1, 2),  # first 3 of degree 3
    ]

    # Build Vandermonde matrix
    N = len(x)
    A = np.zeros((N, N))
    for i in range(N):
        for j, (px, py) in enumerate(monomials):
            A[i, j] = x[i]**px * y[i]**py

    # U_P = A^{-1} — each row is coefficients of one basis polynomial
    U_P = np.linalg.inv(A)

    out_file = os.path.join(OUTPUT_DIR, "quad8_basis_polys.txt")
    np.savetxt(out_file, U_P, fmt="%.15e",
               header="Quad8 basis polynomials (9x9), synthetic (numpy)")
    print(f"Saved (synthetic): {out_file}")


def generate_mesh_pair():
    """
    Generate a small mesh pair (old and new) for the integration test.
    Old mesh: 2×2 regular grid of Quad8 on [0,2]×[0,2]
    New mesh: same grid but rotated slightly or offset
    """
    def make_quad8_grid(nx, scale=1.0, shift=(0.0, 0.0)):
        """Returns (nodes array (N,4), elements array (M,9)) with 1-indexed IDs."""
        npts = 2 * nx + 1
        h = scale / nx

        nodes = []
        nid = 1
        for j in range(npts):
            for i in range(npts):
                x = i * h * 0.5 + shift[0]
                y = j * h * 0.5 + shift[1]
                nodes.append([nid, x, y, 0.0])
                nid += 1

        elements = []
        eid = 1
        for ej in range(nx):
            for ei in range(nx):
                ci = 2 * ei
                cj = 2 * ej
                def nidx(di, dj):
                    return (cj + dj) * npts + (ci + di) + 1  # 1-indexed
                # Quad8: 4 corners + 4 midsides
                corners  = [nidx(0,0), nidx(2,0), nidx(2,2), nidx(0,2)]
                midsides = [nidx(1,0), nidx(2,1), nidx(1,2), nidx(0,1)]
                elements.append([eid] + corners + midsides)
                eid += 1

        return np.array(nodes, dtype=float), np.array(elements, dtype=int)

    nodes_old, elems_old = make_quad8_grid(2, scale=2.0)
    nodes_new, elems_new = make_quad8_grid(2, scale=2.0, shift=(0.05, 0.05))

    # Save mesh files
    np.savetxt(os.path.join(OUTPUT_DIR, "integration_test_mesh_old.txt"),
               nodes_old, fmt="%i, %.10f, %.10f, %.10f",
               header="id, x, y, z")
    np.savetxt(os.path.join(OUTPUT_DIR, "integration_test_mesh_new.txt"),
               nodes_new, fmt="%i, %.10f, %.10f, %.10f",
               header="id, x, y, z")

    # Save element files alongside nodes (same base name)
    np.savetxt(os.path.join(OUTPUT_DIR, "integration_test_elements_old.txt"),
               elems_old, fmt="%i",
               header="id, n1, n2, n3, n4, n5, n6, n7, n8")
    np.savetxt(os.path.join(OUTPUT_DIR, "integration_test_elements_new.txt"),
               elems_new, fmt="%i",
               header="id, n1, n2, n3, n4, n5, n6, n7, n8")

    # Generate field data: u(x,y) = 1 + 2x + 3y  (exact linear field)
    field_rows = []
    for e_row in elems_old:
        eid = int(e_row[0])
        node_ids = e_row[1:] - 1  # → 0-indexed
        coords = nodes_old[node_ids, 1:3]  # x, y

        for ipt, (xi, eta) in enumerate(gauss_pts_quad8()):
            N = quad8_shape(xi, eta)
            x = N @ coords[:, 0]
            y = N @ coords[:, 1]
            u = 1.0 + 2.0 * x + 3.0 * y
            field_rows.append([eid, ipt + 1, u])

    fd = np.array(field_rows)
    np.savetxt(os.path.join(OUTPUT_DIR, "integration_test_field_data.txt"),
               fd, fmt="%i %i %.15e",
               header="elem_id ipt_id u")

    # Expected output: same field evaluated at new mesh Gauss points
    expected_rows = []
    for e_row in elems_new:
        eid = int(e_row[0])
        node_ids = e_row[1:] - 1
        coords = nodes_new[node_ids, 1:3]

        for ipt, (xi, eta) in enumerate(gauss_pts_quad8()):
            N = quad8_shape(xi, eta)
            x = N @ coords[:, 0]
            y = N @ coords[:, 1]
            u = 1.0 + 2.0 * x + 3.0 * y
            expected_rows.append([eid, ipt + 1, u])

    exp = np.array(expected_rows)
    np.savetxt(os.path.join(OUTPUT_DIR, "integration_test_expected_output.txt"),
               exp, fmt="%i %i %.15e",
               header="elem_id ipt_id u_expected")

    print(f"Saved mesh pair and field data to: {OUTPUT_DIR}")


if __name__ == "__main__":
    print(f"Output directory: {OUTPUT_DIR}")
    print()
    print("Generating basis polynomial reference data...")
    generate_basis_reference()
    print()
    print("Generating mesh pair and field data...")
    generate_mesh_pair()
    print()
    print("Done. Reference data files:")
    for fn in sorted(os.listdir(OUTPUT_DIR)):
        fp = os.path.join(OUTPUT_DIR, fn)
        print(f"  {fn}  ({os.path.getsize(fp)} bytes)")
